/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmpleadosGUI;

/**
 *
 * @author jonhe
 */
public class Cargos extends javax.swing.JPanel {

    /**
     * Creates new form CargosP
     */
    public Cargos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        RazonSocial2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Identificador2 = new javax.swing.JTextField();
        Registar2 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        Consultar3 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        Buscar3 = new javax.swing.JButton();
        RazonSocialConsulta4 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        IdentificadorConsulta4 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        Actualizar3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 750));
        setMinimumSize(new java.awt.Dimension(1000, 750));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Título");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));
        jPanel5.add(RazonSocial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 212, -1));

        jLabel6.setText("Salario");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));
        jPanel5.add(Identificador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 212, -1));

        Registar2.setText("Registrar");
        jPanel5.add(Registar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));
        jPanel5.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 296, 1070, 10));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Título", "Salario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable4);

        jPanel5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 980, 156));

        Consultar3.setText("Consultar");
        jPanel5.add(Consultar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 600, -1, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 28, 290));

        Buscar3.setText("Buscar");
        jPanel5.add(Buscar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));
        jPanel5.add(RazonSocialConsulta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 212, -1));

        jLabel24.setText("Salario");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 165, -1));
        jPanel5.add(IdentificadorConsulta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 212, -1));

        jLabel25.setText("Nombre");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        Actualizar3.setText("Actualizar");
        Actualizar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actualizar3Actualizar1ActionPerformed(evt);
            }
        });
        jPanel5.add(Actualizar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, -1, -1));

        jLabel3.setText("Registrar nuevo cargo");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jLabel4.setText("Actualizar cargo previamente registrado");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));

        jLabel7.setText("Consultar cargos registrados");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 344, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estampado.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Actualizar3Actualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actualizar3Actualizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Actualizar3Actualizar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar3;
    private javax.swing.JButton Buscar3;
    private javax.swing.JButton Consultar3;
    private javax.swing.JTextField Identificador2;
    private javax.swing.JTextField IdentificadorConsulta4;
    private javax.swing.JTextField RazonSocial2;
    private javax.swing.JTextField RazonSocialConsulta4;
    private javax.swing.JButton Registar2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
