/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Auditoria;

import Interfaces.Modulo;

/**
 *
 * @author jonhe
 */
public class Auditoria extends javax.swing.JPanel {

    /**
     * Creates new form AuditoriaP
     */
    public Auditoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        FechaInicio = new com.github.lgooddatepicker.components.CalendarPanel();
        FechaFin = new com.github.lgooddatepicker.components.CalendarPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ConsultarIntervaloDeTiempo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1100, 850));
        setMinimumSize(new java.awt.Dimension(1100, 850));
        setPreferredSize(new java.awt.Dimension(1100, 850));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Fecha inicio de consulta");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 22, -1, -1));

        jLabel18.setText("Fecha fin de consulta");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 22, -1, -1));
        add(FechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 54, -1, 201));
        add(FechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 54, -1, 201));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha y hora de transacción", "Tipo de transacción", "Usuario", "Empleado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 307, 940, 375));

        ConsultarIntervaloDeTiempo.setText("Consultar");
        add(ConsultarIntervaloDeTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 266, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estampado.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 790));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultarIntervaloDeTiempo;
    private com.github.lgooddatepicker.components.CalendarPanel FechaFin;
    private com.github.lgooddatepicker.components.CalendarPanel FechaInicio;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
