/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InventarioGUI;

/**
 *
 * @author jonhe
 */
public class Proveedores extends javax.swing.JPanel {

    /**
     * Creates new form ProveedoresP
     */
    public Proveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        PantallaInicial = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        RazonSocial2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        Identificador2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        CorreoElectronico2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        FechaDeInscripcion2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        NumeroDeTelefonoConvencional2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        NumeroDeTelefonoCelular2 = new javax.swing.JTextField();
        Registar2 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        NumeroDeTelefonoConvencionalConsulta2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        NumeroDeTelefonoCelularConsulta2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        Buscar1 = new javax.swing.JButton();
        RazonSocialConsulta2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        IdentificadorConsulta2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        CorreoElectronicoConsulta2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Actualizar1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        RazonSocialConsulta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaClientes = new javax.swing.JList<>();
        IdentificadorConsulta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CorreoElectronicoConsulta = new javax.swing.JTextField();
        FechaDeInscripcionConsulta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        NumeroDeTelefonoConvencionalConsulta = new javax.swing.JTextField();
        NumeroDeTelefonoCelularConsulta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Consultar = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        RazonSocialConsulta1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaClientes1 = new javax.swing.JList<>();
        IdentificadorConsulta1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CorreoElectronicoConsulta1 = new javax.swing.JTextField();
        FechaDeInscripcionConsulta1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        NumeroDeTelefonoConvencionalConsulta1 = new javax.swing.JTextField();
        NumeroDeTelefonoCelularConsulta1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        Consultar1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1100, 850));
        setMinimumSize(new java.awt.Dimension(1100, 850));
        setPreferredSize(new java.awt.Dimension(1100, 850));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estampado.jpg"))); // NOI18N
        jLabel36.setText("jLabel12");

        javax.swing.GroupLayout PantallaInicialLayout = new javax.swing.GroupLayout(PantallaInicial);
        PantallaInicial.setLayout(PantallaInicialLayout);
        PantallaInicialLayout.setHorizontalGroup(
            PantallaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1401, Short.MAX_VALUE)
            .addGroup(PantallaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PantallaInicialLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel36)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PantallaInicialLayout.setVerticalGroup(
            PantallaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1046, Short.MAX_VALUE)
            .addGroup(PantallaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PantallaInicialLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel36)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(PantallaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 850));

        jLabel28.setText("Nombre completo");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 62, -1, -1));
        jPanel1.add(RazonSocial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 212, -1));

        jLabel29.setText("Cédula/RUC");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 93, -1, -1));
        jPanel1.add(Identificador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 212, -1));

        jLabel30.setText("Correo electrónico");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 124, -1, -1));
        jPanel1.add(CorreoElectronico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 212, -1));

        jLabel31.setText("Fecha de inscripción");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 155, -1, -1));

        FechaDeInscripcion2.setEditable(false);
        FechaDeInscripcion2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(FechaDeInscripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 212, -1));

        jLabel32.setText("Número de teléfono convencional");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 186, -1, -1));
        jPanel1.add(NumeroDeTelefonoConvencional2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 212, -1));

        jLabel33.setText("Número de teléfono celular");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 217, -1, -1));
        jPanel1.add(NumeroDeTelefonoCelular2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 212, -1));

        Registar2.setText("Registrar");
        Registar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registar2ActionPerformed(evt);
            }
        });
        jPanel1.add(Registar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, -1));

        jLabel34.setText("Dirección");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 248, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 212, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 324, 990, 10));
        jPanel1.add(NumeroDeTelefonoConvencionalConsulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 497, 212, -1));

        jLabel21.setText("Número de teléfono celular");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 531, -1, -1));
        jPanel1.add(NumeroDeTelefonoCelularConsulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 528, 212, -1));

        jLabel22.setText("Cédula/RUC");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 398, -1, -1));

        Buscar1.setText("Buscar");
        jPanel1.add(Buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 394, -1, -1));
        jPanel1.add(RazonSocialConsulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 395, 212, -1));

        jLabel23.setText("Dirección");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 562, -1, -1));

        jLabel24.setText("Nombre completo");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 438, 165, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 559, 212, -1));
        jPanel1.add(IdentificadorConsulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 435, 212, -1));

        jLabel25.setText("Correo electrónico");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 469, -1, -1));
        jPanel1.add(CorreoElectronicoConsulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 466, 212, -1));

        jLabel26.setText("Número de teléfono convencional");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, -1, -1));

        Actualizar1.setText("Actualizar");
        Actualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actualizar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Actualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 597, -1, -1));

        jLabel27.setText("Registro de nuevos proveedores");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 11, -1, -1));

        jLabel35.setText("Actualización de información de proveedores");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 345, -1, -1));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estampado.jpg"))); // NOI18N
        jLabel46.setText("jLabel12");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 880));

        jTabbedPane1.addTab("Registrar Proveedor", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Nombre");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 126, -1, -1));
        jPanel2.add(RazonSocialConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 123, 212, -1));

        ListaClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Proveedor 1", "Proveedor 2", "Proveedor 3", "Proveedor 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaClientes);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 161, 212, 182));

        IdentificadorConsulta.setEditable(false);
        IdentificadorConsulta.setBackground(new java.awt.Color(204, 204, 204));
        IdentificadorConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdentificadorConsultaActionPerformed(evt);
            }
        });
        jPanel2.add(IdentificadorConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 361, 212, -1));

        jLabel13.setText("Cédula/RUC");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 364, -1, -1));

        jLabel12.setText("Correo electrónico");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 402, -1, -1));

        CorreoElectronicoConsulta.setEditable(false);
        CorreoElectronicoConsulta.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(CorreoElectronicoConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 399, 212, -1));

        FechaDeInscripcionConsulta.setEditable(false);
        FechaDeInscripcionConsulta.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(FechaDeInscripcionConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 437, 212, -1));

        jLabel11.setText("Fecha de inscripción");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));

        jLabel10.setText("Número de teléfono convencional");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 478, -1, -1));

        NumeroDeTelefonoConvencionalConsulta.setEditable(false);
        NumeroDeTelefonoConvencionalConsulta.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(NumeroDeTelefonoConvencionalConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 475, 212, -1));

        NumeroDeTelefonoCelularConsulta.setEditable(false);
        NumeroDeTelefonoCelularConsulta.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(NumeroDeTelefonoCelularConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 513, 212, -1));

        jLabel8.setText("Número de teléfono celular");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 516, -1, -1));

        Consultar.setText("Consultar");
        jPanel2.add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 589, -1, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 551, 212, -1));

        jLabel16.setText("Dirección");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 554, -1, -1));

        jLabel14.setText("Consulta de proveedores");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 52, -1, -1));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estampado.jpg"))); // NOI18N
        jLabel47.setText("jLabel12");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 900));

        jTabbedPane1.addTab("Actualizar Proveedor", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Nombre");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 126, -1, -1));
        jPanel3.add(RazonSocialConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 123, 212, -1));

        ListaClientes1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Proveedor 1", "Proveedor 2", "Proveedor 3", "Proveedor 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListaClientes1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 161, 212, 182));

        IdentificadorConsulta1.setEditable(false);
        IdentificadorConsulta1.setBackground(new java.awt.Color(204, 204, 204));
        IdentificadorConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdentificadorConsulta1ActionPerformed(evt);
            }
        });
        jPanel3.add(IdentificadorConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 361, 212, -1));

        jLabel17.setText("Cédula/RUC");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 364, -1, -1));

        jLabel18.setText("Correo electrónico");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 402, -1, -1));

        CorreoElectronicoConsulta1.setEditable(false);
        CorreoElectronicoConsulta1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(CorreoElectronicoConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 399, 212, -1));

        FechaDeInscripcionConsulta1.setEditable(false);
        FechaDeInscripcionConsulta1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(FechaDeInscripcionConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 437, 212, -1));

        jLabel19.setText("Fecha de inscripción");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));

        jLabel20.setText("Número de teléfono convencional");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 478, -1, -1));

        NumeroDeTelefonoConvencionalConsulta1.setEditable(false);
        NumeroDeTelefonoConvencionalConsulta1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(NumeroDeTelefonoConvencionalConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 475, 212, -1));

        NumeroDeTelefonoCelularConsulta1.setEditable(false);
        NumeroDeTelefonoCelularConsulta1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(NumeroDeTelefonoCelularConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 513, 212, -1));

        jLabel37.setText("Número de teléfono celular");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 516, -1, -1));

        Consultar1.setText("Consultar");
        jPanel3.add(Consultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 589, -1, -1));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 551, 212, -1));

        jLabel38.setText("Dirección");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 554, -1, -1));

        jLabel39.setText("Consulta de proveedores");
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 52, -1, -1));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estampado.jpg"))); // NOI18N
        jLabel48.setText("jLabel12");
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 900));

        jTabbedPane1.addTab("Consultar Proveedor", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Registar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Registar2ActionPerformed

    private void Actualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actualizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Actualizar1ActionPerformed

    private void IdentificadorConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdentificadorConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdentificadorConsultaActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        if (jTabbedPane1.getSelectedIndex() == 0 && jPanel1.getX() > evt.getX() && 31 > evt.getY()) {
            PantallaInicial.setVisible(false);
        } else if (jTabbedPane1.getSelectedIndex() != 0){
            PantallaInicial.setVisible(false);
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void IdentificadorConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdentificadorConsulta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdentificadorConsulta1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar1;
    private javax.swing.JButton Buscar1;
    private javax.swing.JButton Consultar;
    private javax.swing.JButton Consultar1;
    private javax.swing.JTextField CorreoElectronico2;
    private javax.swing.JTextField CorreoElectronicoConsulta;
    private javax.swing.JTextField CorreoElectronicoConsulta1;
    private javax.swing.JTextField CorreoElectronicoConsulta2;
    private javax.swing.JTextField FechaDeInscripcion2;
    private javax.swing.JTextField FechaDeInscripcionConsulta;
    private javax.swing.JTextField FechaDeInscripcionConsulta1;
    private javax.swing.JTextField Identificador2;
    private javax.swing.JTextField IdentificadorConsulta;
    private javax.swing.JTextField IdentificadorConsulta1;
    private javax.swing.JTextField IdentificadorConsulta2;
    private javax.swing.JList<String> ListaClientes;
    private javax.swing.JList<String> ListaClientes1;
    private javax.swing.JTextField NumeroDeTelefonoCelular2;
    private javax.swing.JTextField NumeroDeTelefonoCelularConsulta;
    private javax.swing.JTextField NumeroDeTelefonoCelularConsulta1;
    private javax.swing.JTextField NumeroDeTelefonoCelularConsulta2;
    private javax.swing.JTextField NumeroDeTelefonoConvencional2;
    private javax.swing.JTextField NumeroDeTelefonoConvencionalConsulta;
    private javax.swing.JTextField NumeroDeTelefonoConvencionalConsulta1;
    private javax.swing.JTextField NumeroDeTelefonoConvencionalConsulta2;
    private javax.swing.JPanel PantallaInicial;
    private javax.swing.JTextField RazonSocial2;
    private javax.swing.JTextField RazonSocialConsulta;
    private javax.swing.JTextField RazonSocialConsulta1;
    private javax.swing.JTextField RazonSocialConsulta2;
    private javax.swing.JButton Registar2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
