/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SaludGUI;

/**
 *
 * @author jonhe
 */
public class AtencionVeterinaria extends javax.swing.JPanel {

    /**
     * Creates new form Veterinario
     */
    public AtencionVeterinaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        RazonSocial2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        Identificador2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        CorreoElectronico2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        FechaDeInscripcion2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        NumeroDeTelefonoConvencional2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        NumeroDeTelefonoCelular2 = new javax.swing.JTextField();
        Registar2 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        NumeroDeTelefonoConvencionalConsulta2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        NumeroDeTelefonoCelularConsulta2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        Buscar1 = new javax.swing.JButton();
        RazonSocialConsulta2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        IdentificadorConsulta2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        CorreoElectronicoConsulta2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Actualizar1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        RazonSocialConsulta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaClientes = new javax.swing.JList<>();
        IdentificadorConsulta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CorreoElectronicoConsulta = new javax.swing.JTextField();
        FechaDeInscripcionConsulta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        NumeroDeTelefonoConvencionalConsulta = new javax.swing.JTextField();
        NumeroDeTelefonoCelularConsulta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Consultar = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel42 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jTextField15 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField16 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jTextField10 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jList9 = new javax.swing.JList<>();
        jButton9 = new javax.swing.JButton();
        jScrollPane19 = new javax.swing.JScrollPane();
        jList14 = new javax.swing.JList<>();
        jScrollPane20 = new javax.swing.JScrollPane();
        jList15 = new javax.swing.JList<>();
        jButton12 = new javax.swing.JButton();
        jLabel80 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        datePicker2 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel90 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane21 = new javax.swing.JScrollPane();
        jList16 = new javax.swing.JList<>();
        jLabel52 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jTextField23 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField24 = new javax.swing.JTextField();
        jScrollPane22 = new javax.swing.JScrollPane();
        jList17 = new javax.swing.JList<>();
        jLabel84 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jScrollPane23 = new javax.swing.JScrollPane();
        jList18 = new javax.swing.JList<>();
        jLabel85 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        datePicker5 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel91 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        calendarPanel1 = new com.github.lgooddatepicker.components.CalendarPanel();
        calendarPanel2 = new com.github.lgooddatepicker.components.CalendarPanel();
        jButton5 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel95 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        datePicker4 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel66 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jList10 = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        ListaClientes5 = new javax.swing.JList<>();
        RazonSocialConsulta6 = new javax.swing.JTextField();
        CorreoElectronico1 = new javax.swing.JTextField();
        Registar1 = new javax.swing.JButton();
        IdentificadorConsulta6 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        ListaClientes6 = new javax.swing.JList<>();
        CorreoElectronico4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        datePicker6 = new com.github.lgooddatepicker.components.DatePicker();
        jScrollPane24 = new javax.swing.JScrollPane();
        jList19 = new javax.swing.JList<>();
        jLabel74 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jScrollPane25 = new javax.swing.JScrollPane();
        jList20 = new javax.swing.JList<>();
        jScrollPane16 = new javax.swing.JScrollPane();
        ListaClientes7 = new javax.swing.JList<>();
        jLabel39 = new javax.swing.JLabel();
        CorreoElectronicoConsulta3 = new javax.swing.JTextField();
        Actualizar2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        IdentificadorConsulta3 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        ListaClientes8 = new javax.swing.JList<>();
        RazonSocialConsulta5 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        CorreoElectronicoConsulta5 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        RazonSocialConsulta4 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        IdentificadorConsulta4 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jScrollPane26 = new javax.swing.JScrollPane();
        jList21 = new javax.swing.JList<>();
        jButton15 = new javax.swing.JButton();
        jLabel79 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jScrollPane27 = new javax.swing.JScrollPane();
        jList22 = new javax.swing.JList<>();
        datePicker7 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel94 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 750));
        setMinimumSize(new java.awt.Dimension(1000, 750));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1000, 750));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1000, 750));
        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1000, 750));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setText("Nombre completo");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 62, -1, -1));
        jPanel1.add(RazonSocial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 212, -1));

        jLabel29.setText("Cédula/RUC");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 93, -1, -1));
        jPanel1.add(Identificador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 212, -1));

        jLabel30.setText("Correo electrónico");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 124, -1, -1));
        jPanel1.add(CorreoElectronico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 212, -1));

        jLabel31.setText("Fecha de inscripción");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 155, -1, -1));

        FechaDeInscripcion2.setEditable(false);
        FechaDeInscripcion2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(FechaDeInscripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 212, -1));

        jLabel32.setText("Número de teléfono convencional");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 186, -1, -1));
        jPanel1.add(NumeroDeTelefonoConvencional2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 212, -1));

        jLabel33.setText("Número de teléfono celular");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 217, -1, -1));
        jPanel1.add(NumeroDeTelefonoCelular2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 212, -1));

        Registar2.setText("Registrar");
        Registar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registar2ActionPerformed(evt);
            }
        });
        jPanel1.add(Registar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, -1));

        jLabel34.setText("Dirección");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 248, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 212, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 324, 800, 10));
        jPanel1.add(NumeroDeTelefonoConvencionalConsulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 497, 212, -1));

        jLabel21.setText("Número de teléfono celular");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 531, -1, -1));
        jPanel1.add(NumeroDeTelefonoCelularConsulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 528, 212, -1));

        jLabel22.setText("Cédula/RUC");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 398, -1, -1));

        Buscar1.setText("Buscar");
        jPanel1.add(Buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 394, -1, -1));
        jPanel1.add(RazonSocialConsulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 395, 212, -1));

        jLabel23.setText("Dirección");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 562, -1, -1));

        jLabel24.setText("Nombre completo");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 438, 165, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 559, 212, -1));
        jPanel1.add(IdentificadorConsulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 435, 212, -1));

        jLabel25.setText("Correo electrónico");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 469, -1, -1));
        jPanel1.add(CorreoElectronicoConsulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 466, 212, -1));

        jLabel26.setText("Número de teléfono convencional");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 500, -1, -1));

        Actualizar1.setText("Actualizar");
        Actualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actualizar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Actualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 597, -1, -1));

        jLabel27.setText("Registro de nuevo veterinario");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 11, -1, -1));

        jLabel35.setText("Actualización de información de veterinario");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 345, -1, -1));

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estampado.jpg"))); // NOI18N
        jLabel61.setText("jLabel12");
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        jTabbedPane1.addTab("Registrar/actualizar veterinario", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Nombre");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 126, -1, -1));
        jPanel2.add(RazonSocialConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 123, 212, -1));

        ListaClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Veterinario 1", "Veterinario 2", "Veterinario 3", "Veterinario 4", "Veterinario 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaClientes);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 161, 212, 182));

        IdentificadorConsulta.setEditable(false);
        IdentificadorConsulta.setBackground(new java.awt.Color(204, 204, 204));
        IdentificadorConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdentificadorConsultaActionPerformed(evt);
            }
        });
        jPanel2.add(IdentificadorConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 361, 212, -1));

        jLabel13.setText("Cédula/RUC");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 364, -1, -1));

        jLabel12.setText("Correo electrónico");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 402, -1, -1));

        CorreoElectronicoConsulta.setEditable(false);
        CorreoElectronicoConsulta.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(CorreoElectronicoConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 399, 212, -1));

        FechaDeInscripcionConsulta.setEditable(false);
        FechaDeInscripcionConsulta.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(FechaDeInscripcionConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 437, 212, -1));

        jLabel11.setText("Fecha de inscripción");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 440, -1, -1));

        jLabel10.setText("Número de teléfono convencional");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 478, -1, -1));

        NumeroDeTelefonoConvencionalConsulta.setEditable(false);
        NumeroDeTelefonoConvencionalConsulta.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(NumeroDeTelefonoConvencionalConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 475, 212, -1));

        NumeroDeTelefonoCelularConsulta.setEditable(false);
        NumeroDeTelefonoCelularConsulta.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(NumeroDeTelefonoCelularConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 513, 212, -1));

        jLabel8.setText("Número de teléfono celular");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 516, -1, -1));

        Consultar.setText("Consultar");
        jPanel2.add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 589, -1, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 551, 212, -1));

        jLabel16.setText("Dirección");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 554, -1, -1));

        jLabel14.setText("Consulta de veterinario");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 52, -1, -1));

        jLabel88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estampado.jpg"))); // NOI18N
        jLabel88.setText("jLabel12");
        jPanel2.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        jTabbedPane1.addTab("Consultar veterinario", jPanel2);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Registro de atención veterinaria");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel2.setText("Arete de ganado");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 81, -1, -1));
        jPanel5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 176, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ganado 1", "Ganado 2", "Ganado 3", "Ganado 4", "Ganado 5", "Ganado 6", "Ganado 7", "Ganado 8", "Ganado 9", "Ganado 10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 176, 117));

        jLabel42.setText("Estado de salud");
        jPanel5.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 422, -1, -1));
        jPanel5.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 176, -1));

        jLabel43.setText("Fecha de atención veterinaria");
        jPanel5.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 536, -1, -1));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 176, -1));

        jButton1.setText("Registrar");
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 660, -1, -1));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 176, -1));

        jLabel44.setText("Hora de atención veterinaria");
        jPanel5.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 574, 143, -1));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Veterinario 1", "Veterinario 2", "Veterinario 3", "Veterinario 4", "Veterinario 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(jList2);

        jPanel5.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 176, 117));
        jPanel5.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 176, -1));

        jLabel3.setText("Veterinario");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 249, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sano", "Enfermo medio", "Enfermo grave" }));
        jPanel5.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 176, -1));
        jPanel5.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 176, -1));

        jLabel59.setText("Descripción");
        jPanel5.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 460, -1, -1));

        jLabel60.setText("Precio");
        jPanel5.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 498, -1, -1));

        jLabel89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estampado.jpg"))); // NOI18N
        jLabel89.setText("jLabel12");
        jPanel5.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        jTabbedPane1.addTab("Registro de atención veterinaria", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setText("Fecha de registro");
        jPanel6.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 123, -1, -1));

        jLabel47.setText("Actualización de atención veterinaria");
        jPanel6.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 76, -1, -1));

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ganado 1", "Ganado 2", "Ganado 3", "Ganado 4", "Ganado 5", "Ganado 6", "Ganado 7", "Ganado 8", "Ganado 9", "Ganado 10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4);

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 329, 176, 117));
        jPanel6.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 291, 176, -1));

        jLabel17.setText("Actualización de arete");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 294, 152, -1));

        jLabel76.setText("Descripción");
        jPanel6.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 673, -1, -1));
        jPanel6.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 670, 176, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sano", "Enfermo medio", "Enfermo grave" }));
        jPanel6.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 632, 176, -1));

        jLabel18.setText("Actualización de Veterinario");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 462, -1, -1));
        jPanel6.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 459, 176, -1));
        jPanel6.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 708, 176, -1));

        jLabel45.setText("Estado de salud");
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 635, -1, -1));

        jList9.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Veterinario 1", "Veterinario 2", "Veterinario 3", "Veterinario 4", "Veterinario 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane14.setViewportView(jList9);

        jPanel6.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 497, 176, 117));

        jButton9.setText("Actualizar");
        jPanel6.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 746, -1, -1));

        jList14.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Hora 1", "Hora 2", "Hora 3", "Hora 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane19.setViewportView(jList14);

        jPanel6.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 212, 176, 35));

        jList15.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ganado 1", "Ganado 2", "Ganado 3", "Ganado 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane20.setViewportView(jList15);

        jPanel6.add(jScrollPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 159, 176, 35));

        jButton12.setText("Buscar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 224, -1, -1));

        jLabel80.setText("Arete");
        jPanel6.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 163, -1, -1));

        jLabel51.setText("Hora");
        jPanel6.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 212, -1, -1));

        jLabel4.setText("Precio");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 711, -1, -1));
        jPanel6.add(datePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        jLabel90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estampado.jpg"))); // NOI18N
        jLabel90.setText("jLabel12");
        jPanel6.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        jTabbedPane1.addTab("Actualización de atención veterinaria", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList16.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Veterinario 1", "Veterinario 2", "Veterinario 3", "Veterinario 4", "Veterinario 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList16.setEnabled(false);
        jScrollPane21.setViewportView(jList16);

        jPanel7.add(jScrollPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 510, 176, 117));

        jLabel52.setText("Hora");
        jPanel7.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 157, -1, -1));

        jLabel49.setText("Consulta individual de atención veterinaria");
        jPanel7.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 21, -1, -1));

        jLabel53.setText("Estado de salud");
        jPanel7.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 648, -1, -1));

        jLabel83.setText("Arete");
        jPanel7.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 108, -1, -1));

        jLabel54.setText("Fecha de registro");
        jPanel7.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 68, -1, -1));

        jButton13.setText("Buscar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 169, -1, -1));

        jTextField23.setEditable(false);
        jTextField23.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 472, 176, -1));

        jLabel55.setText("Actualización de Veterinario");
        jPanel7.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 475, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sano", "Enfermo medio", "Enfermo grave" }));
        jComboBox4.setEnabled(false);
        jPanel7.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 645, 176, -1));

        jTextField24.setEditable(false);
        jTextField24.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 683, 176, -1));

        jList17.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Hora 1", "Hora 2", "Hora 3", "Hora 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane22.setViewportView(jList17);

        jPanel7.add(jScrollPane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 157, 176, 35));

        jLabel84.setText("Descripción");
        jPanel7.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 686, -1, -1));

        jLabel62.setText("Actualización de arete");
        jPanel7.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 307, 152, -1));

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 304, 176, -1));

        jList5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ganado 1", "Ganado 2", "Ganado 3", "Ganado 4", "Ganado 5", "Ganado 6", "Ganado 7", "Ganado 8", "Ganado 9", "Ganado 10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList5.setEnabled(false);
        jScrollPane5.setViewportView(jList5);

        jPanel7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 342, 176, 117));

        jList18.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ganado 1", "Ganado 2", "Ganado 3", "Ganado 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane23.setViewportView(jList18);

        jPanel7.add(jScrollPane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 104, 176, 35));

        jLabel85.setText("Precio");
        jPanel7.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 724, -1, -1));

        jTextField13.setEditable(false);
        jTextField13.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 721, 176, -1));
        jPanel7.add(datePicker5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estampado.jpg"))); // NOI18N
        jLabel91.setText("jLabel12");
        jPanel7.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        jTabbedPane1.addTab("Consulta individual de atención veterinaria", jPanel7);

        jPanel8.setPreferredSize(new java.awt.Dimension(1000, 750));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setText("Consulta por intervalos de fecha");
        jPanel8.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 18, -1, -1));

        jLabel57.setText("Fecha inicio");
        jPanel8.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 43, -1, -1));

        jLabel58.setText("Fecha fin");
        jPanel8.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));
        jPanel8.add(calendarPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 75, -1, 201));
        jPanel8.add(calendarPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, 201));

        jButton5.setText("Consultar");
        jPanel8.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Hora", "Arete", "Veterinario", "Salud", "Descripción", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable1);

        jPanel8.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 640, 337));

        jLabel95.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estampado.jpg"))); // NOI18N
        jLabel95.setText("jLabel12");
        jPanel8.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        jTabbedPane1.addTab("Consulta por intervalos de fecha de atención veterinaria", jPanel8);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setText("Registro de nuevo tratamiento veterinario");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 73, -1, -1));

        jLabel64.setText("Arete");
        jPanel3.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 168, -1, -1));

        jButton7.setText("Buscar");
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));
        jPanel3.add(datePicker4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 212, -1));

        jLabel66.setText("Fecha de atención veterinaria");
        jPanel3.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 129, -1, -1));

        jList6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ganado 1", "Ganado 2", "Ganado 3", "Ganado 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(jList6);

        jPanel3.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 212, 35));

        jLabel41.setText("Hora");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 221, -1, -1));

        jList10.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Hora 1", "Hora 2", "Hora 3", "Hora 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane15.setViewportView(jList10);

        jPanel3.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 212, 35));

        ListaClientes5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Enfermedad 1", "Enfermedad 2", "Enfermedad 3", "Enfermedad 4", "Enfermedad 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(ListaClientes5);

        jPanel3.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 212, 36));
        jPanel3.add(RazonSocialConsulta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 212, -1));

        CorreoElectronico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoElectronico1ActionPerformed(evt);
            }
        });
        jPanel3.add(CorreoElectronico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 212, -1));

        Registar1.setText("Registrar");
        Registar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registar1ActionPerformed(evt);
            }
        });
        jPanel3.add(Registar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 620, -1, -1));
        jPanel3.add(IdentificadorConsulta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 212, -1));

        jLabel36.setText("Medicina");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 472, 88, -1));

        ListaClientes6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Medicina 1", "Medicina 2", "Medicina 3", "Medicina 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane13.setViewportView(ListaClientes6);

        jPanel3.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 212, 36));
        jPanel3.add(CorreoElectronico4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, 212, -1));

        jLabel7.setText("Descripción");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 595, -1, -1));

        jLabel37.setText("Enfermedad");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 318, -1, -1));

        jLabel5.setText("Dosis");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 564, -1, -1));

        jLabel92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estampado.jpg"))); // NOI18N
        jLabel92.setText("jLabel12");
        jPanel3.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        jTabbedPane1.addTab("Registrar tratamiento veterinario", jPanel3);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setText("Actualización de información de tratamiento veterinario");
        jPanel9.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 58, -1, -1));
        jPanel9.add(datePicker6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 210, -1));

        jList19.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Hora 1", "Hora 2", "Hora 3", "Hora 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane24.setViewportView(jList19);

        jPanel9.add(jScrollPane24, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 212, 35));

        jLabel74.setText("Fecha de atención veterinaria");
        jPanel9.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 92, 160, -1));

        jLabel77.setText("Hora");
        jPanel9.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 191, -1, -1));

        jLabel78.setText("Arete");
        jPanel9.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 138, -1, -1));

        jButton14.setText("Buscar");
        jPanel9.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jList20.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ganado 1", "Ganado 2", "Ganado 3", "Ganado 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane25.setViewportView(jList20);

        jPanel9.add(jScrollPane25, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 212, 35));

        ListaClientes7.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Medicina 1", "Medicina 2", "Medicina 3", "Medicina 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane16.setViewportView(ListaClientes7);

        jPanel9.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 212, 36));

        jLabel39.setText("Dosis");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 494, -1, -1));
        jPanel9.add(CorreoElectronicoConsulta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 212, -1));

        Actualizar2.setText("Actualizar");
        Actualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actualizar2ActionPerformed(evt);
            }
        });
        jPanel9.add(Actualizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, -1, -1));
        jPanel9.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 212, -1));

        jLabel15.setText("Descripción");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 532, -1, -1));

        jLabel40.setText("Medicina");
        jPanel9.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 402, 88, -1));
        jPanel9.add(IdentificadorConsulta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 212, -1));

        ListaClientes8.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Enfermedad 1", "Enfermedad 2", "Enfermedad 3", "Enfermedad 4", "Enfermedad 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(ListaClientes8);

        jPanel9.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 212, 36));
        jPanel9.add(RazonSocialConsulta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 212, -1));

        jLabel50.setText("Enfermedad");
        jPanel9.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 309, -1, -1));

        jLabel93.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estampado.jpg"))); // NOI18N
        jLabel93.setText("jLabel12");
        jPanel9.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        jTabbedPane1.addTab("Actualizar tratamiento veterinario", jPanel9);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setText("Consulta de tratamientos veterinarios");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 71, -1, -1));

        CorreoElectronicoConsulta5.setEditable(false);
        CorreoElectronicoConsulta5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.add(CorreoElectronicoConsulta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 212, -1));

        jLabel68.setText("Enfermedad");
        jPanel4.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 379, -1, -1));

        jTextField17.setEditable(false);
        jTextField17.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 212, -1));

        RazonSocialConsulta4.setEditable(false);
        RazonSocialConsulta4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.add(RazonSocialConsulta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 212, -1));

        jLabel71.setText("Descripción");
        jPanel4.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 476, -1, -1));

        jLabel72.setText("Medicina");
        jPanel4.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 417, 88, -1));

        IdentificadorConsulta4.setEditable(false);
        IdentificadorConsulta4.setBackground(new java.awt.Color(204, 204, 204));
        IdentificadorConsulta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdentificadorConsulta4ActionPerformed(evt);
            }
        });
        jPanel4.add(IdentificadorConsulta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 212, -1));

        jLabel73.setText("Dosis");
        jPanel4.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 448, -1, -1));

        jList21.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ganado 1", "Ganado 2", "Ganado 3", "Ganado 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane26.setViewportView(jList21);

        jPanel4.add(jScrollPane26, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 212, 35));

        jButton15.setText("Buscar");
        jPanel4.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        jLabel79.setText("Arete");
        jPanel4.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 169, -1, -1));

        jLabel81.setText("Hora");
        jPanel4.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 222, -1, -1));

        jLabel82.setText("Fecha de atención veterinaria");
        jPanel4.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 123, 160, -1));

        jList22.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Hora 1", "Hora 2", "Hora 3", "Hora 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane27.setViewportView(jList22);

        jPanel4.add(jScrollPane27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 212, 35));
        jPanel4.add(datePicker7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 210, -1));

        jLabel94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estampado.jpg"))); // NOI18N
        jLabel94.setText("jLabel12");
        jPanel4.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        jTabbedPane1.addTab("Consultar tratamiento veterinario", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1091, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Registar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Registar2ActionPerformed

    private void Actualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actualizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Actualizar1ActionPerformed

    private void IdentificadorConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdentificadorConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdentificadorConsultaActionPerformed

    private void IdentificadorConsulta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdentificadorConsulta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdentificadorConsulta4ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void CorreoElectronico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoElectronico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoElectronico1ActionPerformed

    private void Registar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Registar1ActionPerformed

    private void Actualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actualizar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Actualizar2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar1;
    private javax.swing.JButton Actualizar2;
    private javax.swing.JButton Buscar1;
    private javax.swing.JButton Consultar;
    private javax.swing.JTextField CorreoElectronico1;
    private javax.swing.JTextField CorreoElectronico2;
    private javax.swing.JTextField CorreoElectronico4;
    private javax.swing.JTextField CorreoElectronicoConsulta;
    private javax.swing.JTextField CorreoElectronicoConsulta2;
    private javax.swing.JTextField CorreoElectronicoConsulta3;
    private javax.swing.JTextField CorreoElectronicoConsulta5;
    private javax.swing.JTextField FechaDeInscripcion2;
    private javax.swing.JTextField FechaDeInscripcionConsulta;
    private javax.swing.JTextField Identificador2;
    private javax.swing.JTextField IdentificadorConsulta;
    private javax.swing.JTextField IdentificadorConsulta2;
    private javax.swing.JTextField IdentificadorConsulta3;
    private javax.swing.JTextField IdentificadorConsulta4;
    private javax.swing.JTextField IdentificadorConsulta6;
    private javax.swing.JList<String> ListaClientes;
    private javax.swing.JList<String> ListaClientes5;
    private javax.swing.JList<String> ListaClientes6;
    private javax.swing.JList<String> ListaClientes7;
    private javax.swing.JList<String> ListaClientes8;
    private javax.swing.JTextField NumeroDeTelefonoCelular2;
    private javax.swing.JTextField NumeroDeTelefonoCelularConsulta;
    private javax.swing.JTextField NumeroDeTelefonoCelularConsulta2;
    private javax.swing.JTextField NumeroDeTelefonoConvencional2;
    private javax.swing.JTextField NumeroDeTelefonoConvencionalConsulta;
    private javax.swing.JTextField NumeroDeTelefonoConvencionalConsulta2;
    private javax.swing.JTextField RazonSocial2;
    private javax.swing.JTextField RazonSocialConsulta;
    private javax.swing.JTextField RazonSocialConsulta2;
    private javax.swing.JTextField RazonSocialConsulta4;
    private javax.swing.JTextField RazonSocialConsulta5;
    private javax.swing.JTextField RazonSocialConsulta6;
    private javax.swing.JButton Registar1;
    private javax.swing.JButton Registar2;
    private com.github.lgooddatepicker.components.CalendarPanel calendarPanel1;
    private com.github.lgooddatepicker.components.CalendarPanel calendarPanel2;
    private com.github.lgooddatepicker.components.DatePicker datePicker2;
    private com.github.lgooddatepicker.components.DatePicker datePicker4;
    private com.github.lgooddatepicker.components.DatePicker datePicker5;
    private com.github.lgooddatepicker.components.DatePicker datePicker6;
    private com.github.lgooddatepicker.components.DatePicker datePicker7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList10;
    private javax.swing.JList<String> jList14;
    private javax.swing.JList<String> jList15;
    private javax.swing.JList<String> jList16;
    private javax.swing.JList<String> jList17;
    private javax.swing.JList<String> jList18;
    private javax.swing.JList<String> jList19;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList20;
    private javax.swing.JList<String> jList21;
    private javax.swing.JList<String> jList22;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList6;
    private javax.swing.JList<String> jList9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
