/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentasGUI;

/**
 *
 * @author jonhe
 */
public class Clientes extends javax.swing.JPanel {

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
        /* XD*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        RazonSocial2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        Identificador2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        CorreoElectronico2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        NumeroDeTelefonoConvencional2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        NumeroDeTelefonoCelular2 = new javax.swing.JTextField();
        Registar2 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Identificador7 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        RazonSocial4 = new javax.swing.JTextField();
        Identificador4 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        CorreoElectronico4 = new javax.swing.JTextField();
        NumeroDeTelefonoConvencional4 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        NumeroDeTelefonoCelular4 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        Registar4 = new javax.swing.JButton();
        Registar5 = new javax.swing.JButton();
        Identificador6 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        RazonSocial5 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        Registar6 = new javax.swing.JButton();
        Identificador5 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        CorreoElectronico5 = new javax.swing.JTextField();
        NumeroDeTelefonoConvencional5 = new javax.swing.JTextField();
        NumeroDeTelefonoCelular5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1100, 850));
        setMinimumSize(new java.awt.Dimension(1100, 850));
        setPreferredSize(new java.awt.Dimension(1100, 850));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setText("Nombres y Apellidos o Razon Social");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, 30));
        jPanel1.add(RazonSocial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 212, -1));

        jLabel29.setText("Cédula/RUC");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));
        jPanel1.add(Identificador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 212, -1));

        jLabel30.setText("Correo electrónico");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));
        jPanel1.add(CorreoElectronico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 212, -1));

        jLabel31.setText("Fecha de inscripción");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabel32.setText("Número de teléfono convencional");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));
        jPanel1.add(NumeroDeTelefonoConvencional2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 212, -1));

        jLabel33.setText("Número de teléfono celular");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));
        jPanel1.add(NumeroDeTelefonoCelular2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 212, -1));

        Registar2.setText("Registrar");
        Registar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registar2ActionPerformed(evt);
            }
        });
        jPanel1.add(Registar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));

        jLabel34.setText("Dirección");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 212, -1));

        jLabel27.setText("Registrar Cliente");
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        Identificador7.setEnabled(false);
        jPanel1.add(Identificador7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 212, -1));

        jTabbedPane1.addTab("Registrar Cliente", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setText("Actualizar Cliente");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jLabel44.setText("Nombres y Apellidos o Razon Social");
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, 30));
        jPanel3.add(RazonSocial4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 212, -1));

        Identificador4.setEnabled(false);
        jPanel3.add(Identificador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 212, -1));

        jLabel45.setText("Dirección");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel46.setText("Cédula/RUC");
        jPanel3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));
        jPanel3.add(CorreoElectronico4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 212, -1));
        jPanel3.add(NumeroDeTelefonoConvencional4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 212, -1));

        jLabel49.setText("Correo electrónico");
        jPanel3.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLabel50.setText("Fecha de inscripción");
        jPanel3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));
        jPanel3.add(NumeroDeTelefonoCelular4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 212, -1));

        jLabel51.setText("Número de teléfono convencional");
        jPanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel52.setText("Número de teléfono celular");
        jPanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 212, -1));

        Registar4.setText("Buscar");
        Registar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registar4ActionPerformed(evt);
            }
        });
        jPanel3.add(Registar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        Registar5.setText("Actualizar");
        Registar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registar5ActionPerformed(evt);
            }
        });
        jPanel3.add(Registar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));

        Identificador6.setEnabled(false);
        jPanel3.add(Identificador6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 212, -1));

        jTabbedPane1.addTab("Actualizar Cliente", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel53.setText("Consultar Cliente");
        jPanel2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        RazonSocial5.setEnabled(false);
        jPanel2.add(RazonSocial5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 212, -1));

        jLabel54.setText("Cédula/RUC");
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        Registar6.setText("Buscar");
        Registar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registar6ActionPerformed(evt);
            }
        });
        jPanel2.add(Registar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        Identificador5.setEnabled(false);
        jPanel2.add(Identificador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 212, -1));

        jLabel55.setText("Nombres y Apellidos o Razon Social");
        jPanel2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, 30));

        jLabel56.setText("Dirección");
        jPanel2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        CorreoElectronico5.setEnabled(false);
        jPanel2.add(CorreoElectronico5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 212, -1));

        NumeroDeTelefonoConvencional5.setEnabled(false);
        jPanel2.add(NumeroDeTelefonoConvencional5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 212, -1));

        NumeroDeTelefonoCelular5.setEditable(false);
        NumeroDeTelefonoCelular5.setEnabled(false);
        jPanel2.add(NumeroDeTelefonoCelular5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 212, -1));

        jTextField6.setEditable(false);
        jTextField6.setEnabled(false);
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 212, -1));

        jLabel57.setText("Correo electrónico");
        jPanel2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLabel58.setText("Fecha de inscripción");
        jPanel2.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabel59.setText("Número de teléfono convencional");
        jPanel2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel60.setText("Número de teléfono celular");
        jPanel2.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jTextField7.setEditable(false);
        jTextField7.setEnabled(false);
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 212, -1));

        jTabbedPane1.addTab("Consultar Cliente", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Registar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Registar2ActionPerformed

    private void Registar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Registar4ActionPerformed

    private void Registar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Registar5ActionPerformed

    private void Registar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registar6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Registar6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CorreoElectronico2;
    private javax.swing.JTextField CorreoElectronico4;
    private javax.swing.JTextField CorreoElectronico5;
    private javax.swing.JTextField Identificador2;
    private javax.swing.JTextField Identificador4;
    private javax.swing.JTextField Identificador5;
    private javax.swing.JTextField Identificador6;
    private javax.swing.JTextField Identificador7;
    private javax.swing.JTextField NumeroDeTelefonoCelular2;
    private javax.swing.JTextField NumeroDeTelefonoCelular4;
    private javax.swing.JTextField NumeroDeTelefonoCelular5;
    private javax.swing.JTextField NumeroDeTelefonoConvencional2;
    private javax.swing.JTextField NumeroDeTelefonoConvencional4;
    private javax.swing.JTextField NumeroDeTelefonoConvencional5;
    private javax.swing.JTextField RazonSocial2;
    private javax.swing.JTextField RazonSocial4;
    private javax.swing.JTextField RazonSocial5;
    private javax.swing.JButton Registar2;
    private javax.swing.JButton Registar4;
    private javax.swing.JButton Registar5;
    private javax.swing.JButton Registar6;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
